spring:
  application:
    name: rate-limit-client
server:
  port: 9096
  error:
    include-stacktrace: never

target:
  url: http://localhost:9999
jwt: eyJraWQiOiI3YjdmYWFiOC00ODhiLTQyNjYtOWQzZS1jYzc4OWU3ODk4OTIiLCJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJjNTJiZjdkYi1kYjU1LTRmODktYWM1My04MmI0MGU4YzU3YzIiLCJ3ZWJzaXRlIjoiaHR0cHM6Ly9leGFtcGxlLmNvbSIsInpvbmVpbmZvIjoiRXVyb3BlL0JlcmxpbiIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJwcm9maWxlIjoiaHR0cHM6Ly9leGFtcGxlLmNvbS9id2F5bmUiLCJyb2xlcyI6WyJVU0VSIl0sImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6OTAwMCIsInByZWZlcnJlZF91c2VybmFtZSI6ImJ3YXluZSIsImdpdmVuX25hbWUiOiJCcnVjZSIsImxvY2FsZSI6ImRlLURFIiwiYXVkIjoiZGVtby1jbGllbnQtcGtjZSIsIm5iZiI6MTY5NDU5Mjc5OSwidXBkYXRlZF9hdCI6IjE5NzAtMDEtMDFUMDA6MDA6MDBaIiwic2NvcGUiOlsib3BlbmlkIiwicHJvZmlsZSIsImVtYWlsIl0sIm5hbWUiOiJCcnVjZSBXYXluZSIsIm5pY2tuYW1lIjoiYndheW5lIiwiZXhwIjoxNjk0NTkzNjk5LCJpYXQiOjE2OTQ1OTI3OTksImZhbWlseV9uYW1lIjoiV2F5bmUiLCJlbWFpbCI6ImJydWNlLndheW5lQGV4YW1wbGUuY29tIn0.BX9nFggkNHMeQ1r6Hw3uN6-Z_A0shTAsxTQLOvr0H1_NQWgE4F9mR4NAUPymN0csc4ru42L2EfWRs40FB0g5AP0YONDu6QYxt-vhqvMwFlRYddE7mQZ5sfjemsfs0Iv4cYZjXN_YcE5IcFfl7nMt00kUBOSPiGNSsU5CPm_9R5lkvl_gBviep_8Rj6Ho1euPNCp8bctswyM7P5jjq6qRvyOaqmMZHo5yUtc-3THVNwR8OaD6F3piTUGxRAeJOP8WXANlg5AwXqCswt746JvDCHu9GdiR6JktkBto8HYwNFouKzWkM2d-nwMYJJqZRlyvyfvleJpxE5XHTuV8wygfkQ

logging:
  level:
    web: DEBUG
