spring:
  application:
    name: rate-limit-client
server:
  port: 9096
  error:
    include-stacktrace: never

target:
  url: http://localhost:9999
jwt: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI5NzhkYjI2Yy0wNWFiLTQ1MWItOGU2MS1mOTllMmRlMWMxOTYiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwicm9sZXMiOlsiVVNFUiJdLCJpc3MiOiJ2ZWhpY2xlLXNlcnZpY2UiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJicnVjZS53YXluZUBleGFtcGxlLmNvbSIsImdpdmVuX25hbWUiOiJCcnVjZSIsImF1ZCI6WyJ2ZWhpY2xlLXNlcnZpY2UiXSwic2NvcGUiOiJvcGVuaWQgZW1haWwgcHJvZmlsZSIsIm5hbWUiOiJCcnVjZSBXYXluZSIsImV4cCI6MTY5MTMzMjA0NSwiZmFtaWx5X25hbWUiOiJXYXluZSIsImVtYWlsIjoiYnJ1Y2Uud2F5bmVAZXhhbXBsZS5jb20ifQ.MP1ANSYd4Hbvuvi_mNNjSAyvC8Lfc7ICrmtJ19We_3M

logging:
  level:
    web: DEBUG
