name: Build package

on:
  push:
    branches:
      - '*'
  workflow_dispatch:

permissions: read-all

jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK 17 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'liberica'
          architecture: x64
      - name: Maven build
        run: ./mvnw --batch-mode --update-snapshots verify
      - name: Maven Dependency Tree Dependency Submission
        uses: advanced-security/maven-dependency-submission-action@v3.0.2
